/*
  Copyright (C) 2012 Stuffomatic Ltd. <contact@stuff-o-matic.com>

  All rights reserved.
*/
/**
 * \file
 * \brief Implementation of the sdc::makefile_generator class.
 * \author Julien Jorge
 */
#include "makefile_generator.hpp"

#include <fstream>

#include <boost/algorithm/string/join.hpp>

/*----------------------------------------------------------------------------*/
/**
 * \brief Constructor.
 * \param makefile The path to the makefile to generate.
 * \param command The command to use in the makefile to process a .spritedesc
 *        file.
 */
sdc::makefile_generator::makefile_generator
( std::string makefile, std::string command )
  : m_makefile(makefile), m_command( command )
{

} // makefile_generator::makefile_generator()

/*----------------------------------------------------------------------------*/
/**
 * \brief Generates the images described in a given collection of spritedesc
 *        files.
 * \papam file The files to process.
 */
void sdc::makefile_generator::run( file_to_spritedesc_map file )
{
  std::ostream* output;
  bool output_to_file(false);

  if ( m_makefile == "-" )
    output = &std::cout;
  else
    {
      output = new std::ofstream( m_makefile.c_str() );
      output_to_file = true;
    }

  const std::vector<std::string> dependencies( get_all_output_files( file ) );

  *output << "all: " << boost::algorithm::join( dependencies, " " )
          << "\n\n";

  generate_makefile_rules( *output, file );

  if ( output_to_file )
    delete output;
} // makefile_generator::run()

/*----------------------------------------------------------------------------*/
/**
 * \brief Get the names of all the images generated by the .spritedesc files.
 * \param file The .spritedesc files and their spritesc structures.
 */
std::vector<std::string> sdc::makefile_generator::get_all_output_files
( file_to_spritedesc_map file ) const
{
  std::vector<std::string> result;

  for ( file_to_spritedesc_map::const_iterator it=file.begin();
        it!=file.end(); ++it )
    {
      const std::vector<std::string> desc_files
        ( get_all_output_files( working_directory( it->first ), it->second ) );
      result.insert( result.end(), desc_files.begin(), desc_files.end() );
    }

  return result;
} // makefile_generator::get_all_output_files()

/*----------------------------------------------------------------------------*/
/**
 * \brief Get the names of all the images generated by a given spritedesc.
 * \param dir The directories where the files are searched and written.
 * \param desc The spritedesc to process.
 */
std::vector<std::string> sdc::makefile_generator::get_all_output_files
( working_directory dir, spritedesc_collection desc ) const
{
  std::vector<std::string> result;

  for ( spritedesc_collection::const_iterator it = desc.begin();
        it != desc.end();
        ++it )
    result.push_back( dir.get_output_image_path( it->output_name ) );

  return result;
} // makefile_generator::get_all_output_files()

/*----------------------------------------------------------------------------*/
/**
 * \brief Generates the rules for all the images built by the .spritedesc files.
 * \param output The stream in which the rules are written.
 * \param file The .spritedesc files and their spritesc structures.
 */
void sdc::makefile_generator::generate_makefile_rules
( std::ostream& output, file_to_spritedesc_map file ) const
{
  for ( file_to_spritedesc_map::const_iterator it=file.begin();
        it!=file.end(); ++it )
    generate_makefile_rule( output, working_directory(it->first), it->second );
} // makefile_generator::generate_makefile_rules()

/*----------------------------------------------------------------------------*/
/**
 * \brief Generates a makefile that calls the program to generate the images.
 * \param output The stream in which the rules are writen.
 * \param desc The descriptions of the images.
 */
void sdc::makefile_generator::generate_makefile_rule
( std::ostream& output, working_directory dir,
  std::list<spritedesc> desc ) const
{
  for ( std::list<spritedesc>::const_iterator it=desc.begin(); it!=desc.end();
        ++it )
    generate_makefile_rule( output, dir, *it );
} // makefile_generator::generate_makefile_rule()

/*----------------------------------------------------------------------------*/
/**
 * \brief Generates a makefile that calls the program to generate an image.
 * \param output The stream in which the rule is written.
 * \param desc The description of the image to generate with the rule.
 */
void sdc::makefile_generator::generate_makefile_rule
( std::ostream& output, working_directory dir, spritedesc desc ) const
{
  output << dir.get_output_image_path( desc.output_name ) << ':';

  std::vector<std::string> xcf_files;

  for ( spritedesc::id_to_file_map::const_iterator xcf_it = desc.xcf.begin();
        xcf_it != desc.xcf.end(); ++xcf_it )
    output << ' ' <<  dir.get_xcf_path( xcf_it->second );

  output << ' ' << dir.get_input_file_name() << "\n";
  output << "\t" << m_command << " --target=\"" << desc.output_name << "\" "
         << dir.get_input_file_name() << "\n\n";
} // makefile_generator::generate_makefile_rule()
